---
- name: Install packages for munin master
  package:
    name: munin
    state: present
  tags: install

- name: munin config
  template:
    src: munin.conf.j2
    dest: "{{ munin_includedir }}/ansible.conf"
  tags: config

- name: nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/munin.conf
  tags: config
  notify: reload nginx
